language: node_js
node_js:
  - '6'

addons:
  ssh_known_hosts: corvus.club

script:
  - npm run gulp
  - cp -r assets index.html -t build/

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ffa476b0a0d0_key -iv $encrypted_ffa476b0a0d0_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ travis@corvus.club:/srv/http/codeparrot
  on:
    branch: master
